{% set name = "autogluon" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/autogluon/autogluon/archive/5cc799b1ac88a967e1a7fdac9e8594ca7475c2c5.tar.gz
  sha256: 4bc97b77dd44ec7dbdb8a9767388eff055cd5d933226ef87d30b9f99fc8bf2b2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./autogluon -vv
  number: 2
  script_env:
    - RELEASE=1

requirements:
  host:
    - python >=3.8,<3.11
    - pip
  run:
    - python >=3.8,<3.11
    - autogluon.core =={{ version }}
    - autogluon.features =={{ version }}
    - autogluon.tabular =={{ version }}
    - autogluon.multimodal =={{ version }}
    - autogluon.timeseries =={{ version }}

test:
  imports:
    - autogluon
  # commands:
  #   - python -c "from autogluon.version import __version__ as v; assert v == '{{ version }}', f'{v} != {{ version }}'"
  requires:
    - pip

about:
  home: https://pypi.org/project/autogluon
  summary: AutoML for Image, Text, and Tabular Data
  description: |
    AutoGluon automates machine learning tasks enabling you to easily achieve strong 
    predictive performance in your applications. With just a few lines of code, you 
    can train and deploy high-accuracy machine learning and deep learning models on 
    image, text, time series, and tabular data.
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yinweisu
    - Innixma
    - giswqs
